version: "3"
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: practice
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
volumes:
  db_data:
